name: state_management
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  provider: 5.0.0
  flutter_bloc: ^7.1.0
  uuid: 2.2.2
  cupertino_icons: ^1.0.0
  mockito: ^4.1.2

dev_dependencies:
  bloc_test: ^8.1.0
  test_api: ^0.2.19-nullsafety


flutter:
  uses-material-design: true