name: state_management
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  provider: 5.0.0
  flutter_bloc: ^7.1.0
  uuid: ^3.0.4
  cupertino_icons: ^1.0.0
  mockito: ^5.0.14
  crypto: ^3.0.0

dev_dependencies:
  bloc_test: ^8.1.0
  test_api: ^0.4.2


flutter:
  uses-material-design: true